# Generated by Django 3.2.6 on 2021-08-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='name',
            field=models.CharField(default="<class 'datetime.date'>", max_length=60),
        ),
        migrations.AlterField(
            model_name='memories',
            name='date',
            field=models.DateField(),
        ),
    ]
